services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"  # Expose PostgreSQL on the default port 5432
    environment:
      POSTGRES_USER: postgres  # Replace with your PostgreSQL username
      POSTGRES_PASSWORD: POSTGRES_PASSWORD  # Replace with your PostgreSQL password
      POSTGRES_DB: mental_health  # The name of your database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
  app:
    build:
      context: .  # Build context set to the current directory
      dockerfile: Dockerfile  # Name of your Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"  # Expose port 8501 for Streamlit
    volumes:
      - .:/app  # Mount the current directory to `/app` in the container
    environment:
      - PYTHONUNBUFFERED=1  # Ensure unbuffered logging in Docker Compose as well
    depends_on:
      - postgres  # Wait for PostgreSQL to be ready before starting Streamlit

  

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Expose Grafana on its default port 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=GRAFANA_ADMIN_PASSWORD  # Set Grafana's admin password
    depends_on:
      - postgres  # Wait for PostgreSQL to be ready before starting Grafana
    volumes:
      - grafana_data:/var/lib/grafana  # Persist Grafana data

volumes:
  postgres_data:  # Named volume for PostgreSQL data persistence
  grafana_data:  # Named volume for Grafana data persistence